// Ampere-native layer-resident FP8 projection scheduler probe.
// Compact E4M3/E8M0 weights remain byte-resident. One persistent launch runs
// q_a -> {q_b + indexer, wkv} -> wo_a -> wo_b with real BF16 dependencies.

#include <cuda_bf16.h>
#include <cuda_runtime.h>

#include <algorithm>
#include <bit>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace {
constexpr std::uint32_t kWarp=32,kWarps=4,kThreads=128;
std::uint32_t kResidentBlocksPerSm=4;
constexpr std::uint32_t kWarmups=3,kSamples=11;
constexpr std::size_t kMiB=1ULL<<20,kScrubBytes=256ULL*kMiB,
                      kRulerBytes=128ULL*kMiB,kCeiling=512ULL*kMiB;

void check(cudaError_t s,std::string_view w){if(s!=cudaSuccess)throw std::runtime_error(std::string(w)+": "+cudaGetErrorString(s));}
class Buffer{public:explicit Buffer(std::size_t n):n_(n){check(cudaMalloc(&p_,n),"cudaMalloc scheduler");}~Buffer(){if(p_)cudaFree(p_);}void*get()const{return p_;}std::size_t bytes()const{return n_;}private:void*p_{};std::size_t n_{};};
std::uint32_t rng(std::uint32_t&x){x^=x<<13;x^=x>>17;x^=x<<5;return x;}
std::uint16_t bf16_bits(float x){auto b=std::bit_cast<std::uint32_t>(x);b+=0x7fffU+((b>>16)&1U);return std::uint16_t(b>>16);}
float bf16_value(std::uint16_t b){return std::bit_cast<float>(std::uint32_t(b)<<16);}
float e4(std::uint8_t c){auto e=(c>>3)&15U,m=c&7U;float v=e?std::ldexp(1.0F+float(m)/8.0F,int(e)-7):std::ldexp(float(m),-9);return(c&0x80U)?-v:v;}
float e8(std::uint8_t s){return std::ldexp(1.0F,int(s)-127);}

__device__ __forceinline__ std::uint32_t decode_pair(std::uint32_t pair,std::uint32_t factor){const auto p=__byte_perm(pair,0U,0x4140U);const std::uint32_t v=((p<<8)&0x80008000U)|((p<<4)&0x07f007f0U);const auto r=__hmul2(*reinterpret_cast<const __nv_bfloat162*>(&v),*reinterpret_cast<const __nv_bfloat162*>(&factor));return *reinterpret_cast<const std::uint32_t*>(&r);}
__device__ __forceinline__ void mma(float&d0,float&d1,float&d2,float&d3,std::uint32_t a0,std::uint32_t a1,std::uint32_t a2,std::uint32_t a3,std::uint32_t b0,std::uint32_t b1){asm volatile("mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32 {%0,%1,%2,%3},{%4,%5,%6,%7},{%8,%9},{%0,%1,%2,%3};\n":"+f"(d0),"+f"(d1),"+f"(d2),"+f"(d3):"r"(a0),"r"(a1),"r"(a2),"r"(a3),"r"(b0),"r"(b1));}
__device__ __forceinline__ std::uint16_t round_bf16(float x){std::uint32_t b=__float_as_uint(x);b+=0x7fffU+((b>>16)&1U);return std::uint16_t(b>>16);}

__device__ __forceinline__ float device_bf16(std::uint16_t bits){return __uint_as_float(std::uint32_t(bits)<<16U);}
__device__ __forceinline__ std::uint32_t normalize_pair(std::uint32_t values,std::uint32_t weights,float inverse){const auto lo=round_bf16(device_bf16(std::uint16_t(values))*inverse*device_bf16(std::uint16_t(weights)));const auto hi=round_bf16(device_bf16(std::uint16_t(values>>16U))*inverse*device_bf16(std::uint16_t(weights>>16U)));return std::uint32_t(lo)|(std::uint32_t(hi)<<16U);}

__device__ __forceinline__ float device_e4m3(std::uint8_t code){const auto exponent=(code>>3U)&15U,mantissa=code&7U;const float magnitude=exponent==0U?ldexpf(float(mantissa),-9):ldexpf(1.0F+float(mantissa)/8.0F,int(exponent)-7);return(code&0x80U)!=0U?-magnitude:magnitude;}
__device__ __forceinline__ float device_e8m0(std::uint8_t code){return ldexpf(1.0F,int(code)-127);}
__device__ __forceinline__ std::uint8_t packed_code_at(const uint4*codes,std::uint32_t row,std::uint32_t column,std::uint32_t k){const std::uint32_t nt=row/16U,local_row=row&15U,kp=column/32U,within=column&31U,half=within/16U,remainder=within&15U,lane=(local_row&7U)*4U+((remainder&7U)/2U),index=(local_row>=8U?2U:0U)+(remainder>=8U?4U:0U)+(remainder&1U),word=half*2U+(remainder>=8U?1U:0U);const auto packed=codes[(std::size_t(nt)*(k/32U)+kp)*kWarp+lane];const auto*words=reinterpret_cast<const std::uint32_t*>(&packed);return std::uint8_t(words[word]>>((index&3U)*8U));}

template<int SPLIT,bool GROUPED=false,bool QNORM_SOURCE=false,bool QNORM_INPUT=false,bool GUARDED=false,int ACCS=2>
__device__ __forceinline__ void process_work(const uint4*codes,const std::uint8_t*scales,const std::uint16_t*x,float*partials,std::uint32_t*counters,std::uint16_t*y,std::uint32_t n,std::uint32_t k,std::uint32_t work,std::uint32_t*arrived,std::uint32_t*replays,double*qnorm_squares=nullptr,float*qnorm_tile_sums=nullptr,const std::uint16_t*qnorm_weight=nullptr,float*qnorm_inverse=nullptr,std::uint32_t*qnorm_state=nullptr,std::uint32_t*replay_rows=nullptr,std::uint32_t*replay_count=nullptr){
 const std::uint32_t lane=threadIdx.x&31U,warp=threadIdx.x>>5U,nt=work/SPLIT,slice=work%SPLIT,kpairs=k/32U,pairs_per_slice=kpairs/SPLIT,pbegin=slice*pairs_per_slice,pend=pbegin+pairs_per_slice,group=lane>>2U,thread=lane&3U;
 x+=GROUPED?std::size_t(nt/64U)*k:0U;
 float accum[ACCS][4]{};
 constexpr int CHUNKS=ACCS>=8?ACCS/8:1;
 for(std::uint32_t pb=pbegin;pb<pend;pb+=4U*CHUNKS){
#pragma unroll
  for(int chunk=0;chunk<CHUNKS;++chunk){const std::uint32_t cpb=pb+std::uint32_t(chunk)*4U,ktb=cpb*2U;std::uint32_t s=lane==0?scales[(nt/8U)*(k/128U)+ktb/8U]:0U;s=__shfl_sync(0xffffffffU,s,0);const std::uint32_t factor=((s+120U)<<7U)*0x00010001U;uint4 q[4];
#pragma unroll
  for(int u=0;u<4;++u)q[u]=codes[(std::size_t(nt)*kpairs+cpb+std::uint32_t(u))*kWarp+lane];
#pragma unroll
  for(int u=0;u<4;++u)
#pragma unroll
   for(int j=0;j<2;++j){const std::uint32_t lo=j==0?q[u].x:q[u].z,hi=j==0?q[u].y:q[u].w;const auto a0=decode_pair(lo&0xffffU,factor),a1=decode_pair(lo>>16,factor),a2=decode_pair(hi&0xffffU,factor),a3=decode_pair(hi>>16,factor);std::uint32_t b0=0,b1=0;if(group==0U){const std::uint32_t kt=ktb+std::uint32_t(u)*2U+std::uint32_t(j);const auto*base=x+kt*16U+thread*2U;b0=*reinterpret_cast<const std::uint32_t*>(base);b1=*reinterpret_cast<const std::uint32_t*>(base+8U);if constexpr(QNORM_INPUT){const auto*weight=qnorm_weight+kt*16U+thread*2U;const float inverse=*qnorm_inverse;b0=normalize_pair(b0,*reinterpret_cast<const std::uint32_t*>(weight),inverse);b1=normalize_pair(b1,*reinterpret_cast<const std::uint32_t*>(weight+8U),inverse);}}const int index=ACCS>=8?chunk*8+u*2+j:j;auto&a=accum[index];mma(a[0],a[1],a[2],a[3],a0,a1,a2,a3,b0,b1);}
  }
 }
#pragma unroll
 for(int step=1;step<ACCS;step*=2)
#pragma unroll
  for(int base=0;base<ACCS;base+=step*2)
#pragma unroll
   for(int reg=0;reg<4;++reg)accum[base][reg]+=accum[base+step][reg];
 float*dst=partials+(std::size_t(nt)*SPLIT+slice)*128U+lane*4U;dst[0]=accum[0][0];dst[1]=accum[0][1];dst[2]=accum[0][2];dst[3]=accum[0][3];__threadfence();if(lane==0)arrived[warp]=atomicAdd(counters+nt,1U);__syncwarp();if(arrived[warp]!=SPLIT-1U)return;
 float norm_square=0.0F,fast_value=0.0F;std::uint32_t midpoint_distance=0xffffffffU;if(lane<16U){const std::uint32_t nr=lane,source=(nr&7U)*4U,reg=(nr>>3U)*2U;double sum=0.0;
#pragma unroll
  for(std::uint32_t sk=0;sk<SPLIT;++sk)sum+=double(partials[(std::size_t(nt)*SPLIT+sk)*128U+source*4U+reg]);fast_value=float(sum);const auto output_index=nt*16U+nr;const auto bits=round_bf16(fast_value);y[output_index]=bits;const auto tail=__float_as_uint(fast_value)&0xffffU;midpoint_distance=tail>0x8000U?tail-0x8000U:0x8000U-tail;if constexpr(QNORM_SOURCE){const double value=double(device_bf16(bits));qnorm_squares[output_index]=value*value;norm_square=float(value*value);}}
 if constexpr(GUARDED){constexpr std::uint32_t guard=ACCS>=8?(GROUPED?64U:16U):(GROUPED?1024U:512U);const auto ambiguous=__ballot_sync(0xffffffffU,lane<16U&&(midpoint_distance<=guard||(fast_value!=0.0F&&fabsf(fast_value)<=1.0e-6F)));const auto count=__popc(ambiguous);std::uint32_t base=0U;if(lane==0U)base=atomicAdd(replay_count,count);base=__shfl_sync(0xffffffffU,base,0);if(lane<16U&&(ambiguous&(1U<<lane))!=0U)replay_rows[base+__popc(ambiguous&((1U<<lane)-1U))]=nt*16U+lane;}
 if constexpr(QNORM_SOURCE){for(int offset=16;offset>0;offset>>=1)norm_square+=__shfl_down_sync(0xffffffffU,norm_square,offset);if(lane==0U){qnorm_tile_sums[nt]=norm_square;if(qnorm_state!=nullptr){__threadfence();if(atomicAdd(qnorm_state,1U)==63U){float square_sum=0.0F;for(std::uint32_t tile=0;tile<64U;++tile)square_sum+=qnorm_tile_sums[tile];*qnorm_inverse=1.0F/sqrtf(square_sum/1024.0F+1.0e-6F);__threadfence();atomicExch(qnorm_state+1,1U);}}}}
 (void)n;(void)replays;
 if(lane==0)counters[nt]=0U;
}

template<bool GROUPED,int REPLAY_SPLIT=8>
__device__ __forceinline__ void replay_rows_split_cta(const uint4*codes,const std::uint8_t*scales,const std::uint16_t*input,std::uint16_t*output,const std::uint32_t*rows,std::uint32_t count,std::uint32_t k,double*partials,std::uint32_t*counters,std::uint32_t*replays,std::uint32_t*done=nullptr,std::uint32_t*epoch=nullptr){__shared__ double warp_sums[kWarps];const std::uint32_t lane=threadIdx.x&31U,warp=threadIdx.x>>5U,total=count*REPLAY_SPLIT;for(std::uint32_t task=blockIdx.x;task<total;task+=gridDim.x){const auto index=task/REPLAY_SPLIT,slice=task%REPLAY_SPLIT,row=rows[index],begin=(k/REPLAY_SPLIT)*slice,end=begin+k/REPLAY_SPLIT;const auto*x=input+(GROUPED?std::size_t(row/1024U)*k:0U);double exact=0.0;for(std::uint32_t column=begin+threadIdx.x;column<end;column+=kThreads){const auto code=packed_code_at(codes,row,column,k);const auto scale=scales[std::size_t(row/128U)*(k/128U)+column/128U];const auto factor=((std::uint32_t(scale)+120U)<<7U)*0x00010001U,pair=std::uint32_t(code)*0x00010001U,decoded=decode_pair(pair,factor);exact+=double(device_bf16(x[column])*device_bf16(std::uint16_t(decoded)));}for(int offset=16;offset>0;offset>>=1)exact+=__shfl_down_sync(0xffffffffU,exact,offset);if(lane==0U)warp_sums[warp]=exact;__syncthreads();exact=threadIdx.x<kWarps?warp_sums[lane]:0.0;for(int offset=16;offset>0;offset>>=1)exact+=__shfl_down_sync(0xffffffffU,exact,offset);if(threadIdx.x==0U){partials[index*REPLAY_SPLIT+slice]=exact;__threadfence();if(atomicAdd(counters+index,1U)==REPLAY_SPLIT-1U){double sum=0.0;for(int part=0;part<REPLAY_SPLIT;++part)sum+=partials[index*REPLAY_SPLIT+part];output[row]=round_bf16(float(sum));atomicAdd(replays,1U);counters[index]=0U;if(done!=nullptr&&atomicAdd(done,1U)==count-1U){atomicExch(done,0U);__threadfence();atomicAdd(epoch,1U);}}}__syncthreads();}}

__device__ __forceinline__ void replay_rows_warp_slices(const uint4*codes,const std::uint8_t*scales,const std::uint16_t*input,std::uint16_t*output,const std::uint32_t*rows,std::uint32_t count,std::uint32_t k,double*partials,std::uint32_t*counters,std::uint32_t*replays){constexpr std::uint32_t slices=32U,groups=slices/kWarps;const std::uint32_t lane=threadIdx.x&31U,warp=threadIdx.x>>5U,total=count*groups;for(std::uint32_t task=blockIdx.x;task<total;task+=gridDim.x){const auto index=task/groups,group=task%groups,row=rows[index],slice=group*kWarps+warp,begin=(k/slices)*slice,end=begin+k/slices;double exact=0.0;for(std::uint32_t column=begin+lane;column<end;column+=kWarp){const auto code=packed_code_at(codes,row,column,k);const auto scale=scales[std::size_t(row/128U)*(k/128U)+column/128U];const auto factor=((std::uint32_t(scale)+120U)<<7U)*0x00010001U,pair=std::uint32_t(code)*0x00010001U,decoded=decode_pair(pair,factor);exact+=double(device_bf16(input[column])*device_bf16(std::uint16_t(decoded)));}for(int offset=16;offset>0;offset>>=1)exact+=__shfl_down_sync(0xffffffffU,exact,offset);if(lane==0U)partials[index*slices+slice]=exact;__syncthreads();if(threadIdx.x==0U){__threadfence();if(atomicAdd(counters+index,kWarps)==slices-kWarps){double sum=0.0;for(std::uint32_t part=0;part<slices;++part)sum+=partials[index*slices+part];output[row]=round_bf16(float(sum));atomicAdd(replays,1U);counters[index]=0U;}}__syncthreads();}}

__device__ void grid_barrier(std::uint32_t*count,std::uint32_t*epoch){__shared__ std::uint32_t seen;if(threadIdx.x==0){seen=atomicAdd(epoch,0U);__threadfence();const auto ticket=atomicAdd(count,1U);if(ticket==gridDim.x-1U){atomicExch(count,0U);__threadfence();atomicAdd(epoch,1U);}else while(atomicAdd(epoch,0U)==seen){}}__syncthreads();}

__device__ void grid_barrier_qnorm(std::uint32_t*count,std::uint32_t*epoch,const std::uint16_t*source,const double*squares,const float*tile_sums,const std::uint16_t*weight,std::uint16_t*output,float*published_inverse,int mode){__shared__ std::uint32_t seen,last;__shared__ float inverse;if(threadIdx.x==0){seen=atomicAdd(epoch,0U);__threadfence();last=atomicAdd(count,1U)==gridDim.x-1U;}__syncthreads();if(last!=0U){if(mode==0){if(threadIdx.x==0){double sum=0.0;for(std::uint32_t i=0;i<1024U;++i)sum=__dadd_rn(sum,squares[i]);inverse=1.0F/sqrtf(float(sum/1024.0)+1.0e-6F);}}else{float sum=0.0F;if(threadIdx.x<kWarp){const std::uint32_t count=mode==2?64U:1024U;for(std::uint32_t i=threadIdx.x;i<count;i+=kWarp)sum+=mode==2?tile_sums[i]:float(squares[i]);for(int offset=16;offset>0;offset>>=1)sum+=__shfl_down_sync(0xffffffffU,sum,offset);if(threadIdx.x==0)inverse=1.0F/sqrtf(sum/1024.0F+1.0e-6F);}}__syncthreads();if(mode==2){if(threadIdx.x==0)*published_inverse=inverse;}else for(std::uint32_t i=threadIdx.x;i<1024U;i+=kThreads)output[i]=round_bf16(device_bf16(source[i])*inverse*device_bf16(weight[i]));__syncthreads();if(threadIdx.x==0){atomicExch(count,0U);__threadfence();atomicAdd(epoch,1U);}}else if(threadIdx.x==0)while(atomicAdd(epoch,0U)==seen){}__syncthreads();}

__device__ void grid_barrier_qnorm_legacy(std::uint32_t*count,std::uint32_t*epoch,const std::uint16_t*source,const std::uint16_t*weight,std::uint16_t*output){__shared__ std::uint32_t seen,last;__shared__ float inverse;if(threadIdx.x==0){seen=atomicAdd(epoch,0U);__threadfence();last=atomicAdd(count,1U)==gridDim.x-1U;}__syncthreads();if(last!=0U){float sum=0.0F;if(threadIdx.x<kWarp){for(std::uint32_t i=threadIdx.x;i<1024U;i+=kWarp){const float value=device_bf16(source[i]);sum+=value*value;}for(int offset=16;offset>0;offset>>=1)sum+=__shfl_down_sync(0xffffffffU,sum,offset);if(threadIdx.x==0)inverse=1.0F/sqrtf(sum/1024.0F+1.0e-6F);}__syncthreads();for(std::uint32_t i=threadIdx.x;i<1024U;i+=kThreads)output[i]=round_bf16(device_bf16(source[i])*inverse*device_bf16(weight[i]));__syncthreads();if(threadIdx.x==0){atomicExch(count,0U);__threadfence();atomicAdd(epoch,1U);}}else if(threadIdx.x==0)while(atomicAdd(epoch,0U)==seen){}__syncthreads();}

template<bool GUARDED>
__global__ __launch_bounds__(kThreads,4) void scheduler_kernel(
 const uint4*qa,const std::uint8_t*qas,const uint4*qb,const std::uint8_t*qbs,const uint4*kv,const std::uint8_t*kvs,const uint4*oa,const std::uint8_t*oas,const uint4*ob,const std::uint8_t*obs,
 const std::uint16_t*input,const std::uint16_t*attention,const std::uint16_t*qnorm,float*pqa,float*pqb,float*pkv,float*poa,float*pob,std::uint32_t*cqa,std::uint32_t*cqb,std::uint32_t*ckv,std::uint32_t*coa,std::uint32_t*cob,
 std::uint16_t*yqa,std::uint16_t*yqr,std::uint16_t*yqb,std::uint16_t*ykv,std::uint16_t*yoa,std::uint16_t*yob,double*qnorm_squares,float*qnorm_tile_sums,float*qnorm_inverse,std::uint32_t*qnorm_state,std::uint32_t*barrier,std::uint32_t*replays,std::uint32_t*replay_rows,std::uint32_t*replay_counts,int qnorm_mode){
 __shared__ std::uint32_t arrived[kWarps];const std::uint32_t pw=blockIdx.x*kWarps+(threadIdx.x>>5U),stride=gridDim.x*kWarps;
 if(qnorm_mode==4){for(std::uint32_t w=pw;w<(1024U/16U)*16U;w+=stride)process_work<16>(qa,qas,input,pqa,cqa,yqa,1024,4096,w,arrived,replays);grid_barrier_qnorm_legacy(barrier,barrier+1,yqa,qnorm,yqr);}else{for(std::uint32_t w=pw;w<(1024U/16U)*16U;w+=stride)process_work<16,false,true>(qa,qas,input,pqa,cqa,yqa,1024,4096,w,arrived,replays,qnorm_squares,qnorm_tile_sums,nullptr,qnorm_inverse,qnorm_mode==3?qnorm_state:nullptr);if(qnorm_mode==3){if(blockIdx.x<8U){while(atomicAdd(qnorm_state+1,0U)==0U){}const auto i=blockIdx.x*kThreads+threadIdx.x;yqr[i]=round_bf16(device_bf16(yqa[i])*(*qnorm_inverse)*device_bf16(qnorm[i]));__syncthreads();if(threadIdx.x==0U){__threadfence();if(atomicAdd(qnorm_state+2,1U)==7U){__threadfence();atomicExch(qnorm_state+3,1U);}}}while(atomicAdd(qnorm_state+3,0U)==0U){}__syncthreads();}else grid_barrier_qnorm(barrier,barrier+1,yqa,qnorm_squares,qnorm_tile_sums,qnorm,yqr,qnorm_inverse,qnorm_mode);}
 constexpr std::uint32_t qbwork=(40960U/16U),kvwork=(512U/16U)*16U;
 for(std::uint32_t w=pw;w<qbwork+kvwork;w+=stride){if(w<qbwork){if(qnorm_mode==2)process_work<1,false,false,true,false,16>(qb,qbs,yqa,pqb,cqb,yqb,40960,1024,w,arrived,replays+1,nullptr,nullptr,qnorm,qnorm_inverse);else process_work<1,false,false,false,GUARDED,16>(qb,qbs,yqr,pqb,cqb,yqb,40960,1024,w,arrived,replays+1,nullptr,nullptr,nullptr,nullptr,nullptr,replay_rows+1024U,replay_counts+1);}else process_work<16>(kv,kvs,input,pkv,ckv,ykv,512,4096,w-qbwork,arrived,replays+2);}
 grid_barrier(barrier,barrier+1);
 if constexpr(GUARDED)replay_rows_warp_slices(qb,qbs,yqr,yqb,replay_rows+1024U,replay_counts[1],1024,reinterpret_cast<double*>(pqb),cqb,replays+1);
 for(std::uint32_t w=pw;w<(8192U/16U)*4U;w+=stride)process_work<4,true,false,false,false,16>(oa,oas,attention,poa,coa,yoa,8192,4096,w,arrived,replays+3);
 grid_barrier(barrier,barrier+1);
 for(std::uint32_t w=pw;w<(4096U/16U)*8U;w+=stride)process_work<8>(ob,obs,yoa,pob,cob,yob,4096,8192,w,arrived,replays+4);
 if(blockIdx.x==0U&&threadIdx.x==0U){replay_counts[1]=0U;replay_counts[3]=0U;}
 if(blockIdx.x==0U&&threadIdx.x==0U){qnorm_state[0]=0U;qnorm_state[1]=0U;qnorm_state[2]=0U;qnorm_state[3]=0U;}
}

__global__ void scrub_kernel(std::uint8_t*p,std::size_t n){for(std::size_t i=std::size_t(blockIdx.x)*blockDim.x+threadIdx.x,s=std::size_t(gridDim.x)*blockDim.x;i<n;i+=s)p[i]=std::uint8_t(i);}
__global__ void ruler_kernel(const uint4*p,std::uint64_t n,unsigned*sink){const std::uint64_t st=std::uint64_t(gridDim.x)*blockDim.x;std::uint64_t i=std::uint64_t(blockIdx.x)*blockDim.x+threadIdx.x;unsigned a=0;for(;i<n;i+=st){auto x=p[i];a^=x.x^x.y^x.z^x.w;}if(a==0xdeadbeefU)sink[threadIdx.x]=a;}
float median(std::vector<float>v){std::sort(v.begin(),v.end());return v[v.size()/2];}
template<class F>float timed(cudaEvent_t a,cudaEvent_t b,cudaStream_t s,F f){check(cudaEventRecord(a,s),"start");f();check(cudaEventRecord(b,s),"stop");check(cudaEventSynchronize(b),"sync");float ms;check(cudaEventElapsedTime(&ms,a,b),"elapsed");return ms*1000.0F;}

struct HostMatrix{std::uint32_t n,k;std::vector<std::uint8_t>canon,scales;std::vector<uint4>packed;HostMatrix(std::uint32_t nn,std::uint32_t kk,std::uint32_t&state):n(nn),k(kk),canon(std::size_t(n)*k),scales(std::size_t(n/128U)*(k/128U)),packed(std::size_t(n/16U)*(k/32U)*32U){for(auto&c:canon){c=std::uint8_t(rng(state));if((c&0x7fU)==0x7fU)c^=1U;}for(auto&s:scales)s=std::uint8_t(114U+rng(state)%7U);for(std::uint32_t nt=0;nt<n/16U;++nt)for(std::uint32_t kp=0;kp<k/32U;++kp)for(std::uint32_t lane=0;lane<32;++lane){std::uint32_t words[4]{};for(std::uint32_t j=0;j<2;++j)for(std::uint32_t i=0;i<8;++i){const bool high=i==2||i==3||i==6||i==7;const auto row=nt*16+(lane>>2)+(high?8:0),col=(kp*2+j)*16+(lane&3)*2+(i&1)+(i>=4?8:0);words[j*2+(i>=4)]|=std::uint32_t(canon[std::size_t(row)*k+col])<<((i&3)*8);}packed[(std::size_t(nt)*(k/32U)+kp)*32+lane]=make_uint4(words[0],words[1],words[2],words[3]);}}std::size_t bytes()const{return canon.size()+scales.size();}};
struct DevMatrix{Buffer code,scale,partial,counter,out;DevMatrix(const HostMatrix&h,std::uint32_t split):code(h.canon.size()),scale(h.scales.size()),partial(std::size_t(h.n/16U)*split*128U*sizeof(float)),counter(std::size_t(h.n/16U)*sizeof(std::uint32_t)),out(std::size_t(h.n)*sizeof(std::uint16_t)){}std::size_t bytes()const{return code.bytes()+scale.bytes()+partial.bytes()+counter.bytes()+out.bytes();}};
struct Error{std::uint32_t bad{};double norm{};};
Error oracle(const HostMatrix&w,const std::vector<std::uint16_t>&x,const std::vector<std::uint16_t>&y,bool grouped=false){Error r;for(std::uint32_t n=0;n<w.n;++n){double sum=0,ab=0;const auto base=grouped?std::size_t(n/1024U)*w.k:0U;for(std::uint32_t k=0;k<w.k;++k){const auto s=w.scales[(n/128U)*(w.k/128U)+k/128U];const double p=double(bf16_value(bf16_bits(e4(w.canon[std::size_t(n)*w.k+k])*e8(s))))*bf16_value(x[base+k]);sum+=p;ab+=std::abs(p);}const auto expected=bf16_bits(float(sum));if(y[n]!=expected)++r.bad;r.norm=std::max(r.norm,std::abs(double(bf16_value(y[n]))-bf16_value(expected))/std::max(ab,1e-30));}return r;}
std::vector<std::uint16_t> normalize(const std::vector<std::uint16_t>&x,const std::vector<std::uint16_t>&weight,bool exact){double sum=0.0;if(exact){for(const auto bits:x){const double value=double(bf16_value(bits));sum+=value*value;}}else{float partial[kWarp]{};for(std::uint32_t thread=0;thread<kWarp;++thread)for(std::uint32_t i=thread;i<1024U;i+=kWarp){const float value=bf16_value(x[i]);partial[thread]+=value*value;}for(std::uint32_t stride=kWarp/2U;stride!=0U;stride>>=1U)for(std::uint32_t i=0;i<stride;++i)partial[i]+=partial[i+stride];sum=partial[0];}const float inverse=1.0F/std::sqrt(float(sum/1024.0)+1.0e-6F);std::vector<std::uint16_t>result(1024U);for(std::uint32_t i=0;i<1024U;++i)result[i]=bf16_bits(bf16_value(x[i])*inverse*bf16_value(weight[i]));return result;}
Error compare_codes(const std::vector<std::uint16_t>&expected,const std::vector<std::uint16_t>&actual){Error result;for(std::size_t i=0;i<expected.size();++i){if(expected[i]!=actual[i])++result.bad;result.norm=std::max(result.norm,std::abs(double(bf16_value(expected[i]))-bf16_value(actual[i])));}return result;}
}

int main(int argc,char**argv){try{
 std::string output;int qnorm_mode=4;bool guarded=true;std::uint32_t resident_blocks_per_sm=kResidentBlocksPerSm;for(int i=1;i<argc;++i){std::string_view f=argv[i];if(f=="--output"&&++i<argc)output=argv[i];else if(f=="--resident-blocks"&&++i<argc)resident_blocks_per_sm=std::stoul(argv[i]);else if(f=="--unguarded")guarded=false;else if(f=="--qnorm"&&++i<argc){const std::string_view mode=argv[i];if(mode=="exact")qnorm_mode=0;else if(mode=="warp")qnorm_mode=1;else if(mode=="fused")qnorm_mode=2;else if(mode=="pipeline")qnorm_mode=3;else if(mode=="legacy")qnorm_mode=4;else throw std::runtime_error("qnorm mode is invalid");}else throw std::runtime_error("usage: --output FILE [--qnorm MODE] [--resident-blocks N] [--unguarded]");}if(resident_blocks_per_sm<3U||resident_blocks_per_sm>7U)throw std::runtime_error("resident blocks must be 3 through 7");kResidentBlocksPerSm=resident_blocks_per_sm;
 if(resident_blocks_per_sm==7U)throw std::runtime_error("seven resident blocks exceed the scheduler barrier occupancy");
 if(guarded&&qnorm_mode!=4)throw std::runtime_error("guarded replay currently requires legacy query normalization");
 check(cudaSetDevice(0),"device");cudaDeviceProp prop{};check(cudaGetDeviceProperties(&prop,0),"properties");if(prop.major!=8||prop.minor!=6)throw std::runtime_error("requires SM86");
 std::uint32_t state=0x514a9c31U;HostMatrix qa(1024,4096,state),qb(40960,1024,state),kv(512,4096,state),oa(8192,4096,state),ob(4096,8192,state);DevMatrix dqa(qa,16),dqb(qb,1),dkv(kv,16),doa(oa,4),dob(ob,8);
 std::vector<std::uint16_t>input(4096),attention(32768),qnorm(1024,bf16_bits(1.0F));for(auto&v:input)v=bf16_bits(float(int(rng(state)%17)-8)/8.0F);for(auto&v:attention)v=bf16_bits(float(int(rng(state)%17)-8)/8.0F);
 Buffer din(input.size()*2),datt(attention.size()*2),dnorm(qnorm.size()*2),yqr(qnorm.size()*2),qnorm_squares(1024U*sizeof(double)),qnorm_tile_sums(64U*sizeof(float)),qnorm_inverse(sizeof(float)),qnorm_state(4U*sizeof(std::uint32_t)),barrier(8),replays(5*sizeof(std::uint32_t)),replay_rows(54784U*sizeof(std::uint32_t)),replay_counts(20U*sizeof(std::uint32_t)),scrub(kScrubBytes),ruler(kRulerBytes),sink(1024);
 const std::size_t peak=dqa.bytes()+dqb.bytes()+dkv.bytes()+doa.bytes()+dob.bytes()+din.bytes()+datt.bytes()+dnorm.bytes()+yqr.bytes()+qnorm_squares.bytes()+qnorm_tile_sums.bytes()+qnorm_inverse.bytes()+qnorm_state.bytes()+barrier.bytes()+replays.bytes()+replay_rows.bytes()+replay_counts.bytes()+scrub.bytes()+ruler.bytes()+sink.bytes();if(peak>kCeiling)throw std::runtime_error("exceeds 512 MiB");
 cudaStream_t st;check(cudaStreamCreateWithFlags(&st,cudaStreamNonBlocking),"stream");auto upload=[&](const HostMatrix&h,DevMatrix&d){check(cudaMemcpyAsync(d.code.get(),h.packed.data(),d.code.bytes(),cudaMemcpyHostToDevice,st),"code");check(cudaMemcpyAsync(d.scale.get(),h.scales.data(),d.scale.bytes(),cudaMemcpyHostToDevice,st),"scale");check(cudaMemsetAsync(d.counter.get(),0,d.counter.bytes(),st),"counter");};upload(qa,dqa);upload(qb,dqb);upload(kv,dkv);upload(oa,doa);upload(ob,dob);
 check(cudaMemcpyAsync(din.get(),input.data(),din.bytes(),cudaMemcpyHostToDevice,st),"input");check(cudaMemcpyAsync(datt.get(),attention.data(),datt.bytes(),cudaMemcpyHostToDevice,st),"attention");check(cudaMemcpyAsync(dnorm.get(),qnorm.data(),dnorm.bytes(),cudaMemcpyHostToDevice,st),"qnorm");check(cudaMemsetAsync(qnorm_state.get(),0,qnorm_state.bytes(),st),"qnorm state");check(cudaMemsetAsync(barrier.get(),0,barrier.bytes(),st),"barrier");check(cudaMemsetAsync(replays.get(),0,replays.bytes(),st),"replays");check(cudaMemsetAsync(replay_counts.get(),0,replay_counts.bytes(),st),"replay counts");check(cudaMemsetAsync(ruler.get(),0xa5,ruler.bytes(),st),"ruler");check(cudaStreamSynchronize(st),"uploads");
 const auto blocks=prop.multiProcessorCount*kResidentBlocksPerSm;auto run=[&]{auto launch=[&]<bool Guarded>(){scheduler_kernel<Guarded><<<blocks,kThreads,0,st>>>((const uint4*)dqa.code.get(),(const std::uint8_t*)dqa.scale.get(),(const uint4*)dqb.code.get(),(const std::uint8_t*)dqb.scale.get(),(const uint4*)dkv.code.get(),(const std::uint8_t*)dkv.scale.get(),(const uint4*)doa.code.get(),(const std::uint8_t*)doa.scale.get(),(const uint4*)dob.code.get(),(const std::uint8_t*)dob.scale.get(),(const std::uint16_t*)din.get(),(const std::uint16_t*)datt.get(),(const std::uint16_t*)dnorm.get(),(float*)dqa.partial.get(),(float*)dqb.partial.get(),(float*)dkv.partial.get(),(float*)doa.partial.get(),(float*)dob.partial.get(),(std::uint32_t*)dqa.counter.get(),(std::uint32_t*)dqb.counter.get(),(std::uint32_t*)dkv.counter.get(),(std::uint32_t*)doa.counter.get(),(std::uint32_t*)dob.counter.get(),(std::uint16_t*)dqa.out.get(),(std::uint16_t*)yqr.get(),(std::uint16_t*)dqb.out.get(),(std::uint16_t*)dkv.out.get(),(std::uint16_t*)doa.out.get(),(std::uint16_t*)dob.out.get(),(double*)qnorm_squares.get(),(float*)qnorm_tile_sums.get(),(float*)qnorm_inverse.get(),(std::uint32_t*)qnorm_state.get(),(std::uint32_t*)barrier.get(),(std::uint32_t*)replays.get(),(std::uint32_t*)replay_rows.get(),(std::uint32_t*)replay_counts.get(),qnorm_mode);};if(guarded)launch.template operator()<true>();else launch.template operator()<false>();};
 auto doscrub=[&]{scrub_kernel<<<65536,256,0,st>>>((std::uint8_t*)scrub.get(),scrub.bytes());};auto doruler=[&]{ruler_kernel<<<prop.multiProcessorCount*8,256,0,st>>>((const uint4*)ruler.get(),ruler.bytes()/16,(unsigned*)sink.get());};for(unsigned i=0;i<kWarmups;++i){doruler();run();}check(cudaStreamSynchronize(st),"warmups");cudaEvent_t a,b;check(cudaEventCreate(&a),"event");check(cudaEventCreate(&b),"event");std::vector<float>rt,kt;for(unsigned i=0;i<kSamples;++i){doscrub();rt.push_back(timed(a,b,st,doruler));doscrub();kt.push_back(timed(a,b,st,run));}check(cudaGetLastError(),"scheduler");
 auto download=[&](DevMatrix&d,const HostMatrix&h){std::vector<std::uint16_t>v(h.n);check(cudaMemcpy(v.data(),d.out.get(),d.out.bytes(),cudaMemcpyDeviceToHost),"output");return v;};auto yqa=download(dqa,qa),yqb=download(dqb,qb),ykv=download(dkv,kv),yoa=download(doa,oa),yob=download(dob,ob);std::vector<std::uint16_t>yqr_host(1024);check(cudaMemcpy(yqr_host.data(),yqr.get(),yqr.bytes(),cudaMemcpyDeviceToHost),"query norm output");std::uint32_t replay_total[5]{};check(cudaMemcpy(replay_total,replays.get(),replays.bytes(),cudaMemcpyDeviceToHost),"replay counters");
 const auto expected_qr=normalize(yqa,qnorm,qnorm_mode==0);const auto eqa=oracle(qa,input,yqa),eqr=qnorm_mode==2?Error{}:compare_codes(expected_qr,yqr_host),eqb=oracle(qb,qnorm_mode==2?expected_qr:yqr_host,yqb),ekv=oracle(kv,input,ykv),eoa=oracle(oa,attention,yoa,true),eob=oracle(ob,yoa,yob);
 if(qnorm_mode==4)qnorm_mode=1;
 const float ru=median(rt),ku=median(kt);const std::size_t useful=qa.bytes()+qb.bytes()+kv.bytes()+oa.bytes()+ob.bytes();const double rgb=double(kRulerBytes)/ru/1000.0,gb=double(useful)/ku/1000.0;constexpr std::uint32_t runs=kWarmups+kSamples;const std::uint64_t replay_bytes=std::uint64_t(replay_total[0]/runs)*(4096U+32U)+std::uint64_t(replay_total[1]/runs)*(1024U+8U)+std::uint64_t(replay_total[2]/runs)*(4096U+32U)+std::uint64_t(replay_total[3]/runs)*(4096U+32U)+std::uint64_t(replay_total[4]/runs)*(8192U+64U);
 const char*mode_name=qnorm_mode==0?"exact":qnorm_mode==1?"warp":"fused";std::ostream*os=&std::cout;std::ofstream file;if(!output.empty()){file.open(output);os=&file;}*os<<std::fixed<<std::setprecision(9)<<"{\n  \"device_name\": \""<<prop.name<<"\", \"resident_blocks\": "<<blocks<<",\n  \"qnorm_mode\": \""<<mode_name<<"\", \"guarded_replay\": "<<(guarded?"true":"false")<<",\n  \"useful_bytes\": "<<useful<<", \"replay_weight_bytes\": "<<replay_bytes<<", \"peak_device_bytes\": "<<peak<<",\n  \"ruler_us\": "<<ru<<", \"ruler_gbps\": "<<rgb<<",\n  \"scheduler_us\": "<<ku<<", \"effective_gbps\": "<<gb<<", \"roofline_efficiency\": "<<(gb/rgb)<<",\n  \"replay_rows\": ["<<replay_total[0]/runs<<","<<replay_total[1]/runs<<","<<replay_total[2]/runs<<","<<replay_total[3]/runs<<","<<replay_total[4]/runs<<"],\n  \"q_a_mismatches\": "<<eqa.bad<<", \"q_a_maximum_error_over_sum_abs\": "<<eqa.norm<<",\n  \"q_norm_mismatches\": "<<eqr.bad<<", \"q_norm_maximum_absolute\": "<<eqr.norm<<",\n  \"q_b_indexer_mismatches\": "<<eqb.bad<<", \"q_b_indexer_maximum_error_over_sum_abs\": "<<eqb.norm<<",\n  \"wkv_mismatches\": "<<ekv.bad<<", \"wkv_maximum_error_over_sum_abs\": "<<ekv.norm<<",\n  \"wo_a_mismatches\": "<<eoa.bad<<", \"wo_a_maximum_error_over_sum_abs\": "<<eoa.norm<<",\n  \"wo_b_mismatches\": "<<eob.bad<<", \"wo_b_maximum_error_over_sum_abs\": "<<eob.norm<<"\n}\n";cudaEventDestroy(a);cudaEventDestroy(b);cudaStreamDestroy(st);return EXIT_SUCCESS;
}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<'\n';return EXIT_FAILURE;}}
